coverage:
  # Commit status https://docs.codecov.io/docs/commit-status are used
  # to block PR based on coverage threshold.
  status:
    project:
      default:
        target: 80
        # Intentionally to keep the threshold, so that we accept a low test coverage for the development.
        # This value will be adjusted later.
        threshold: 70%
    patch:
      # Disable the coverage threshold of the patch, so that PRs are
      # only failing because of overall project coverage threshold.
      # See https://docs.codecov.io/docs/commit-status#disabling-a-status.
      default: false
comment:
  # Update existing comment or create new if deleted.
  behavior: default
ignore:
  - "**/zz_generated*.go" # Ignore generated files.
  - "pkg/client"
  - "third_party"
  - "vendor"
