run:
  timeout: 5m

  build-tags:
    - e2e

  skip-dirs:
    - pkg/client

linters:
  disable:
    - errcheck
    - asciicheck
    - errorlint
    - gosec
    - prealloc
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam