version: "2"
run:
  build-tags:
    - e2e
linters:
  enable:
    - asciicheck
    - errorlint
    - gosec
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/client
      - third_party
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
