/*
Copyright 2023 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1 "knative.dev/serving-progressive-rollout/pkg/apis/serving/v1"
	servingv1 "knative.dev/serving-progressive-rollout/pkg/client/clientset/versioned/typed/serving/v1"
)

// fakeRolloutOrchestrators implements RolloutOrchestratorInterface
type fakeRolloutOrchestrators struct {
	*gentype.FakeClientWithList[*v1.RolloutOrchestrator, *v1.RolloutOrchestratorList]
	Fake *FakeServingV1
}

func newFakeRolloutOrchestrators(fake *FakeServingV1, namespace string) servingv1.RolloutOrchestratorInterface {
	return &fakeRolloutOrchestrators{
		gentype.NewFakeClientWithList[*v1.RolloutOrchestrator, *v1.RolloutOrchestratorList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("rolloutorchestrators"),
			v1.SchemeGroupVersion.WithKind("RolloutOrchestrator"),
			func() *v1.RolloutOrchestrator { return &v1.RolloutOrchestrator{} },
			func() *v1.RolloutOrchestratorList { return &v1.RolloutOrchestratorList{} },
			func(dst, src *v1.RolloutOrchestratorList) { dst.ListMeta = src.ListMeta },
			func(list *v1.RolloutOrchestratorList) []*v1.RolloutOrchestrator {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.RolloutOrchestratorList, items []*v1.RolloutOrchestrator) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
