/*
Copyright 2023 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "knative.dev/serving-progressive-rollout/pkg/apis/serving/v1"
)

// FakeServiceOrchestrators implements ServiceOrchestratorInterface
type FakeServiceOrchestrators struct {
	Fake *FakeServingV1
	ns   string
}

var serviceorchestratorsResource = v1.SchemeGroupVersion.WithResource("serviceorchestrators")

var serviceorchestratorsKind = v1.SchemeGroupVersion.WithKind("ServiceOrchestrator")

// Get takes name of the serviceOrchestrator, and returns the corresponding serviceOrchestrator object, and an error if there is any.
func (c *FakeServiceOrchestrators) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ServiceOrchestrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serviceorchestratorsResource, c.ns, name), &v1.ServiceOrchestrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceOrchestrator), err
}

// List takes label and field selectors, and returns the list of ServiceOrchestrators that match those selectors.
func (c *FakeServiceOrchestrators) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ServiceOrchestratorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serviceorchestratorsResource, serviceorchestratorsKind, c.ns, opts), &v1.ServiceOrchestratorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ServiceOrchestratorList{ListMeta: obj.(*v1.ServiceOrchestratorList).ListMeta}
	for _, item := range obj.(*v1.ServiceOrchestratorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceOrchestrators.
func (c *FakeServiceOrchestrators) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serviceorchestratorsResource, c.ns, opts))

}

// Create takes the representation of a serviceOrchestrator and creates it.  Returns the server's representation of the serviceOrchestrator, and an error, if there is any.
func (c *FakeServiceOrchestrators) Create(ctx context.Context, serviceOrchestrator *v1.ServiceOrchestrator, opts metav1.CreateOptions) (result *v1.ServiceOrchestrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serviceorchestratorsResource, c.ns, serviceOrchestrator), &v1.ServiceOrchestrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceOrchestrator), err
}

// Update takes the representation of a serviceOrchestrator and updates it. Returns the server's representation of the serviceOrchestrator, and an error, if there is any.
func (c *FakeServiceOrchestrators) Update(ctx context.Context, serviceOrchestrator *v1.ServiceOrchestrator, opts metav1.UpdateOptions) (result *v1.ServiceOrchestrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serviceorchestratorsResource, c.ns, serviceOrchestrator), &v1.ServiceOrchestrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceOrchestrator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceOrchestrators) UpdateStatus(ctx context.Context, serviceOrchestrator *v1.ServiceOrchestrator, opts metav1.UpdateOptions) (*v1.ServiceOrchestrator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(serviceorchestratorsResource, "status", c.ns, serviceOrchestrator), &v1.ServiceOrchestrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceOrchestrator), err
}

// Delete takes name of the serviceOrchestrator and deletes it. Returns an error if one occurs.
func (c *FakeServiceOrchestrators) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(serviceorchestratorsResource, c.ns, name, opts), &v1.ServiceOrchestrator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceOrchestrators) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serviceorchestratorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ServiceOrchestratorList{})
	return err
}

// Patch applies the patch and returns the patched serviceOrchestrator.
func (c *FakeServiceOrchestrators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceOrchestrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serviceorchestratorsResource, c.ns, name, pt, data, subresources...), &v1.ServiceOrchestrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceOrchestrator), err
}
