/*
Copyright 2023 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "knative.dev/serving-progressive-rollout/pkg/apis/serving/v1"
)

// FakeStagePodAutoscalers implements StagePodAutoscalerInterface
type FakeStagePodAutoscalers struct {
	Fake *FakeServingV1
	ns   string
}

var stagepodautoscalersResource = v1.SchemeGroupVersion.WithResource("stagepodautoscalers")

var stagepodautoscalersKind = v1.SchemeGroupVersion.WithKind("StagePodAutoscaler")

// Get takes name of the stagePodAutoscaler, and returns the corresponding stagePodAutoscaler object, and an error if there is any.
func (c *FakeStagePodAutoscalers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.StagePodAutoscaler, err error) {
	emptyResult := &v1.StagePodAutoscaler{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(stagepodautoscalersResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.StagePodAutoscaler), err
}

// List takes label and field selectors, and returns the list of StagePodAutoscalers that match those selectors.
func (c *FakeStagePodAutoscalers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.StagePodAutoscalerList, err error) {
	emptyResult := &v1.StagePodAutoscalerList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(stagepodautoscalersResource, stagepodautoscalersKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.StagePodAutoscalerList{ListMeta: obj.(*v1.StagePodAutoscalerList).ListMeta}
	for _, item := range obj.(*v1.StagePodAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stagePodAutoscalers.
func (c *FakeStagePodAutoscalers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(stagepodautoscalersResource, c.ns, opts))

}

// Create takes the representation of a stagePodAutoscaler and creates it.  Returns the server's representation of the stagePodAutoscaler, and an error, if there is any.
func (c *FakeStagePodAutoscalers) Create(ctx context.Context, stagePodAutoscaler *v1.StagePodAutoscaler, opts metav1.CreateOptions) (result *v1.StagePodAutoscaler, err error) {
	emptyResult := &v1.StagePodAutoscaler{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(stagepodautoscalersResource, c.ns, stagePodAutoscaler, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.StagePodAutoscaler), err
}

// Update takes the representation of a stagePodAutoscaler and updates it. Returns the server's representation of the stagePodAutoscaler, and an error, if there is any.
func (c *FakeStagePodAutoscalers) Update(ctx context.Context, stagePodAutoscaler *v1.StagePodAutoscaler, opts metav1.UpdateOptions) (result *v1.StagePodAutoscaler, err error) {
	emptyResult := &v1.StagePodAutoscaler{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(stagepodautoscalersResource, c.ns, stagePodAutoscaler, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.StagePodAutoscaler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStagePodAutoscalers) UpdateStatus(ctx context.Context, stagePodAutoscaler *v1.StagePodAutoscaler, opts metav1.UpdateOptions) (result *v1.StagePodAutoscaler, err error) {
	emptyResult := &v1.StagePodAutoscaler{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(stagepodautoscalersResource, "status", c.ns, stagePodAutoscaler, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.StagePodAutoscaler), err
}

// Delete takes name of the stagePodAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeStagePodAutoscalers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(stagepodautoscalersResource, c.ns, name, opts), &v1.StagePodAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStagePodAutoscalers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(stagepodautoscalersResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.StagePodAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched stagePodAutoscaler.
func (c *FakeStagePodAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StagePodAutoscaler, err error) {
	emptyResult := &v1.StagePodAutoscaler{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(stagepodautoscalersResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.StagePodAutoscaler), err
}
